[project]
name = "learn-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.2.0",
    "langchain-core>=1.3.1",
    "langchain-openai>=1.2.0",
    "langchain>=1.2.15",
    "langgraph>=1.1.9",
    "openai>=2.17.0",
    "python-dotenv>=1.2.1",
    "skills-ref>=0.1.1",
    "langchain-community>=0.4.1",
    "langchain-experimental>=0.4.1",
    "deepagents>=0.5.3",
    "dashscope>=1.25.17",
    "langmem>=0.0.30",
    "langchain-docker-backend>=1.0.0",
    "fastapi>=0.141.1",
    "uvicorn>=0.52.3",
]
