[project]
name = "learn-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.2.0",
    "langchain-core>=1.2.16",
    "langchain-openai>=1.1.10",
    "langchain>=1.2.10",
    "langgraph>=1.0.8",
    "openai>=2.17.0",
    "python-dotenv>=1.2.1",
    "skills-ref>=0.1.1",
    "langchain-community>=0.4.1",
    "langchain-experimental>=0.4.1",
    "deepagents>=0.5.3",
]
